language: node_js
node_js: node
cache:
  directories:
    - node_modules
script:
  - npm test
env:
  - CI=true

before_deploy:
  - npm install netlify-cli -g
  - npm run build

deploy:
  provider: script
  script: netlify deploy -s 6794c64e-0520-4ddb-b064-1963220e1ef3 -t 0f9ccfb2abcbcb9ad532ae46d96721b077cf50b32b0fa9d0da5c11a7ec92879d -p ./build
  skip_cleanup: true
  on:
    branch: master
